### ISSUE TITLE
Animations all very fast when game is built and run outside of Editor

### ISSUE THREAD

**Issue by jbrigleb** [Tactical-Planning/Tactics-Demo#7]

**Comment by andrewhuntsmith** [comment]
Changed the calculation for unit movement speed in UnitScript, and the movement is now more consistent in builds

**Comment by andrewhuntsmith** [comment]
Fixed the speed for damage text as well in commit 2ae3cdad99b4eb3a2a0b2d2d5b045bef26eb0bcb
